apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
    tier: api
spec:
  containers:
    - name: todo-api
      image: todo-backend:latest
      imagePullPolicy: Never
      env:
        - name: REDIS_HOST
          value: redis-service
      ports:
        - containerPort: 3001
  restartPolicy: Always